// FontAwesome (fa)
import {
  FaFingerprint,
  FaArrowRight,
  FaUser,
  FaStar,
  FaCodeBranch,
  FaGithub,
  FaLinkedin,
  FaInstagram,
  FaTwitter,
  FaCubes,
  FaFileAlt,
  FaSitemap,
  FaBook,
  FaTabletAlt,
  FaAssistiveListeningSystems,
  FaProjectDiagram,
  FaLaptopCode,
  FaTools,
  FaPalette,
  FaMobileAlt,
  FaCode,
  FaLock,
  FaSync,
  FaUsers,
  FaPaintBrush,
  FaSearch,
  FaTachometerAlt,
  FaServer,
  FaChartLine,
  FaBriefcase,
  FaBullhorn,
  FaBullseye,
  FaThumbsUp,
  FaQrcode,
  FaLayerGroup,
  FaGlobe,
  FaSolarPanel,
  FaWindowMaximize,
  FaEnvelope,         // Fallback for mailbox/postman
  FaTerminal,
  FaChrome,
  FaFirefoxBrowser,
  FaSafari,
  FaDatabase,         // Fallback for some tools
  // ...import more as needed
} from 'react-icons/fa'

// Simple Icons (si)
import {
  SiHashnode,
  SiHackerrank,
  SiLeetcode,
  SiMedium,
  SiFigma,
  SiUpwork,
  SiFreelancer,
  SiJavascript,
  SiNodedotjs,
  SiReact,
  SiNextdotjs,
  SiRedux,
  SiWebpack,
  SiGit,
  SiMysql,
  SiMongodb,
  SiHtml5,
  SiCss3,
  SiVscode,
  SiPostman,
  SiJenkins,
  SiAdobexd,
  SiCanva,
  SiAdobephotoshop,
  SiCodepen,
  SiAtom,
  SiGnubash,
  SiTrello,
  SiJira,
  SiSlack,
  SiGooglechrome,
  SiFirefoxbrowser,
  SiSafari,
  SiVercel,
  SiNetlify,
  SiTypescript,
  SiJquery,
  SiTailwindcss,
  SiPhp,
  SiLaravel,
  SiBootstrap,
  SiMaterialui,
  SiSass,
  SiPython,
  SiJava,
  // ...import more as needed
} from 'react-icons/si'

// Game Icons, Dev Icons, etc. for other special/fun icons (if needed)
import { GiCopilot, GiArtificialIntelligence, GiGemini } from 'react-icons/gi'

export const myIconMap = {
  // Socials, tools, brands (existing)
  fingerprint: FaFingerprint,
  arrowRight: FaArrowRight,
  user: FaUser,
  star: FaStar,
  codeBranch: FaCodeBranch,
  github: FaGithub,
  linkedin: FaLinkedin,
  instagram: FaInstagram,
  twitter: FaTwitter,
  medium: SiMedium,
  hashnode: SiHashnode,
  hackerrank: SiHackerrank,
  leetcode: SiLeetcode,
  figma: SiFigma,
  upwork: SiUpwork,
  freelancer: SiFreelancer,

  // Website/app features
  palette: FaPalette,
  'mobile-alt': FaMobileAlt,
  code: FaCode,
  'laptop-code': FaLaptopCode,
  lock: FaLock,
  sync: FaSync,
  users: FaUsers,
  'project-diagram': FaProjectDiagram,
  'paint-brush': FaPaintBrush,
  search: FaSearch,
  'tachometer-alt': FaTachometerAlt,
  server: FaServer,
  'chart-line': FaChartLine,
  briefcase: FaBriefcase,
  bullhorn: FaBullhorn,
  bullseye: FaBullseye,
  'thumbs-up': FaThumbsUp,
  'file-alt': FaFileAlt,
  'file-lines': FaFileAlt,           // alias, FaFileLines if available
  'grid-2-plus': FaTools,
  cubes: FaCubes,
  sitemap: FaSitemap,
  book: FaBook,
  tablet: FaTabletAlt,
  'ear-listen': FaAssistiveListeningSystems,
  'chart-network': FaProjectDiagram, // alias

  // Stack/devicons (existing + new)
  javascript: SiJavascript,
  nodejs: SiNodedotjs,
  react: SiReact,
  nextjs: SiNextdotjs,
  redux: SiRedux,
  webpack: SiWebpack,
  git: SiGit,
  mysql: SiMysql,
  mongodb: SiMongodb,
  html5: SiHtml5,
  css3: SiCss3,
  typescript: SiTypescript,
  jquery: SiJquery,
  tailwindcss: SiTailwindcss,
  php: SiPhp,
  laravel: SiLaravel,
  bootstrap: SiBootstrap,
  materialui: SiMaterialui,
  sass: SiSass,
  python: SiPython,
  java: SiJava,

  // Methods (as before)
  'planet-moon': FaGlobe,
  qrcode: FaQrcode,
  window: FaWindowMaximize,
  'layer-plus': FaLayerGroup,
  'solar-system': FaSolarPanel,
  vscode: SiVscode,
  mailbox: SiPostman,            // Or FaEnvelope as fallback; SiPostman is preferred
  postman: SiPostman,
  jenkins: SiJenkins,
  figma: SiFigma,
  xd: SiAdobexd,
  canva: SiCanva,
  photoshop: SiAdobephotoshop,
  codepen: SiCodepen,
  atom: SiAtom,
  bash: SiGnubash,
  terminal: FaTerminal,
  trello: SiTrello,
  jira: SiJira,
  slack: SiSlack,
  chrome: SiGooglechrome,
  firefox: SiFirefoxbrowser,
  safari: SiSafari,
  vagrant: SiVercel,             // Given your mapping, vagrant key maps to Vercel icon
  vercel: SiVercel,
  'dot-net': SiNetlify,          // Given your mapping, dot-net key maps to Netlify icon
  netlify: SiNetlify,

  // -------- NEW: AI Tools --------
  copilot: GiCopilot,                           // Using GiCopilot for Copilot
  chatgpt: GiArtificialIntelligence,            // Generic AI icon for ChatGPT
  gemini: GiGemini,
  github_devicon: GiCopilot,
}